# MuCloud Bot Python配置文件
account: # 账号相关
  user_id: 123456  # QQ账号（留空则自动获取）
  nick_name: "" #昵称（留空则自动获取）
  bot_admin: []

api: # Api设置
  host: '127.0.0.1'
  port: 5700

server: # 监听服务器设置
  host: '127.0.0.1'
  port: 5701